apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
spec:
  template:
    spec:
      containers:
      - name: velero
        image: velero/velero:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets  # Name of the Kubernetes secret
              key: AWS_ACCESS_KEY_ID  # Key in the secret containing AWS access key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets  # Name of the Kubernetes secret
              key: AWS_SECRET_ACCESS_KEY  # Key in the secret containing AWS secret access key
        # ... other container specifications