apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: democloudops
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      formatter: text
      fields:
        service: registry

    storage:
      cache:
        blobdescriptor: inmemory

      filesystem:
        rootdirectory: /var/lib/registry

    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]

    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd  

    tls:
      certificate: /certs/seron.crt   
      key: /certs/seron.key