apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: democloudops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi